### ISSUE TITLE
Option for hex background color

### ISSUE THREAD

**Issue by JosefJezek** [latitudegeo/showcaser#4]
Could you add option for hex background color with alpha?

- https://stackoverflow.com/questions/5623838/rgb-to-hex-and-hex-to-rgb

**Comment by ianschmitz** [comment]
I'm open to the idea. We would need to maintain the option to specify the alpha channel along with a hex value.

**Comment by JosefJezek** [comment]
Yes, hex + alpha. I need change color based on `hex` MD color palette. 

https://material.io/guidelines/style/color.html#color-color-palette
